<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AssetDailyOdosTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('asset_daily_odos')->truncate();
        
        $data = [
            [
                'id' => '3',
                'reading_date' => '2026-06-22',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '4',
                'old_odo' => '0.00',
                'new_odo' => '500.00',
                'odo_diff' => '500.00',
                'old_hours' => '0.00',
                'new_hours' => '100.00',
                'hours_diff' => '100.00',
                'updated_by' => 'Admin',
                'note' => '',
                'created_at' => '2026-06-22 02:14:59',
                'updated_at' => '2026-06-22 02:14:59',
                'deleted_at' => null,
                'house_id' => '1',
            ],
            [
                'id' => '4',
                'reading_date' => '2026-06-24',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '4',
                'old_odo' => '500.00',
                'new_odo' => '530.00',
                'odo_diff' => '30.00',
                'old_hours' => '100.00',
                'new_hours' => '112.00',
                'hours_diff' => '12.00',
                'updated_by' => 'Admin',
                'note' => '',
                'created_at' => '2026-06-24 15:26:39',
                'updated_at' => '2026-06-24 15:46:58',
                'deleted_at' => null,
                'house_id' => '1',
            ],
            [
                'id' => '5',
                'reading_date' => '2026-06-27',
                'shifts_count' => '1.00',
                'operator' => 'Nguyễn văn Tiến',
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '4',
                'old_odo' => '0.00',
                'new_odo' => '0.00',
                'odo_diff' => '0.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => 'Admin',
                'note' => '',
                'created_at' => '2026-06-27 22:19:56',
                'updated_at' => '2026-06-27 22:19:56',
                'deleted_at' => null,
                'house_id' => '1',
            ],
            [
                'id' => '6',
                'reading_date' => '2026-06-27',
                'shifts_count' => '1.00',
                'operator' => 'Nguyễn Văn Qúa',
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '5',
                'old_odo' => '0.00',
                'new_odo' => '0.00',
                'odo_diff' => '0.00',
                'old_hours' => '0.00',
                'new_hours' => '16.00',
                'hours_diff' => '16.00',
                'updated_by' => 'Admin',
                'note' => '',
                'created_at' => '2026-06-27 22:21:36',
                'updated_at' => '2026-06-27 22:21:36',
                'deleted_at' => null,
                'house_id' => '1',
            ],
            [
                'id' => '7',
                'reading_date' => '2026-06-27',
                'shifts_count' => '1.00',
                'operator' => 'Trịnh văn Và',
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '6',
                'old_odo' => '0.00',
                'new_odo' => '248.00',
                'odo_diff' => '248.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => 'Admin',
                'note' => '',
                'created_at' => '2026-06-27 22:28:33',
                'updated_at' => '2026-06-27 22:28:33',
                'deleted_at' => null,
                'house_id' => '1',
            ],
            [
                'id' => '8',
                'reading_date' => '2026-07-05',
                'shifts_count' => '1.00',
                'operator' => 'HÒA',
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '7',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-07-05 17:48:10',
                'updated_at' => '2026-07-05 17:48:26',
                'deleted_at' => null,
                'house_id' => '1',
            ],
            [
                'id' => '9',
                'reading_date' => '2026-07-13',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '7',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-07-13 14:30:27',
                'updated_at' => '2026-07-13 14:30:52',
                'deleted_at' => null,
                'house_id' => '1',
            ],
            [
                'id' => '10',
                'reading_date' => '2026-07-13',
                'shifts_count' => '16.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '7',
                'old_odo' => '16.00',
                'new_odo' => '16.00',
                'odo_diff' => '0.00',
                'old_hours' => '16.00',
                'new_hours' => '144.00',
                'hours_diff' => '128.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-07-13 16:16:31',
                'updated_at' => '2026-07-13 16:16:31',
                'deleted_at' => null,
                'house_id' => '1',
            ],
            [
                'id' => '11',
                'reading_date' => '2026-07-24',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '7',
                'old_odo' => '16.00',
                'new_odo' => '200.00',
                'odo_diff' => '184.00',
                'old_hours' => '144.00',
                'new_hours' => '194.00',
                'hours_diff' => '50.00',
                'updated_by' => 'Admin',
                'note' => null,
                'created_at' => '2026-07-24 13:49:28',
                'updated_at' => '2026-07-24 13:56:02',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '12',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '8',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:28',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '13',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '9',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '14',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '10',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '15',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '11',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '16',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '12',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '17',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '13',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '18',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '14',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '19',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '15',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '20',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '16',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '21',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '17',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '22',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '18',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '23',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '19',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '24',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '20',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '25',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '21',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '26',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '22',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '27',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '23',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '28',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '24',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '29',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '25',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '30',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '26',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '31',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '27',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '32',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '28',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '33',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '29',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '34',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '30',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '35',
                'reading_date' => '2026-08-03',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '31',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '3',
                'note' => null,
                'created_at' => '2026-08-03 07:35:14',
                'updated_at' => '2026-08-03 09:36:40',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '36',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '4',
                'old_odo' => '530.00',
                'new_odo' => '538.00',
                'odo_diff' => '8.00',
                'old_hours' => '120.00',
                'new_hours' => '128.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '37',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '5',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '38',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '6',
                'old_odo' => '0.00',
                'new_odo' => '8.00',
                'odo_diff' => '8.00',
                'old_hours' => '0.00',
                'new_hours' => '8.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '39',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '8',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '40',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '9',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '41',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '10',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '42',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '11',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '43',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '12',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '44',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '13',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '45',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '14',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '46',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '15',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '47',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '16',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '48',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '17',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '49',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '18',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '50',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '19',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '51',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '20',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '52',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '21',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '53',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '22',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '54',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '23',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '55',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '24',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '56',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '25',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '57',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '26',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '58',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '27',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '59',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '28',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '60',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '29',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '61',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '30',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
            [
                'id' => '62',
                'reading_date' => '2026-08-10',
                'shifts_count' => '1.00',
                'operator' => null,
                'phone' => null,
                'status' => 'approved',
                'is_synced' => '0',
                'asset_id' => '31',
                'old_odo' => '8.00',
                'new_odo' => '16.00',
                'odo_diff' => '8.00',
                'old_hours' => '8.00',
                'new_hours' => '16.00',
                'hours_diff' => '8.00',
                'updated_by' => '1',
                'note' => null,
                'created_at' => '2026-08-10 04:14:02',
                'updated_at' => '2026-08-10 04:14:23',
                'deleted_at' => null,
                'house_id' => null,
            ],
        ];
        
        foreach(array_chunk($data, 100) as $chunk) {
            DB::table('asset_daily_odos')->insert($chunk);
        }
    }
}
