<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaintenanceBomItemsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('maintenance_bom_items')->truncate();
        
        $data = [
            [
                'id' => '15',
                'maintenance_bom_id' => '1',
                'product_id' => '161',
                'quantity' => '1.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-07-13 15:31:53',
                'updated_at' => '2026-07-13 15:31:53',
                'house_id' => '1',
            ],
            [
                'id' => '16',
                'maintenance_bom_id' => '1',
                'product_id' => '392',
                'quantity' => '1.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-07-13 15:31:53',
                'updated_at' => '2026-07-13 15:31:53',
                'house_id' => '1',
            ],
            [
                'id' => '17',
                'maintenance_bom_id' => '1',
                'product_id' => '632',
                'quantity' => '30.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-07-13 15:31:53',
                'updated_at' => '2026-07-13 15:31:53',
                'house_id' => '1',
            ],
            [
                'id' => '18',
                'maintenance_bom_id' => '2',
                'product_id' => '491',
                'quantity' => '28.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-07-13 15:31:53',
                'updated_at' => '2026-07-13 15:31:53',
                'house_id' => '1',
            ],
            [
                'id' => '19',
                'maintenance_bom_id' => '2',
                'product_id' => '184',
                'quantity' => '1.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-07-13 15:31:53',
                'updated_at' => '2026-07-13 15:31:53',
                'house_id' => '1',
            ],
            [
                'id' => '20',
                'maintenance_bom_id' => '2',
                'product_id' => '226',
                'quantity' => '1.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-07-13 15:31:53',
                'updated_at' => '2026-07-13 15:31:53',
                'house_id' => '1',
            ],
            [
                'id' => '21',
                'maintenance_bom_id' => '2',
                'product_id' => '180',
                'quantity' => '1.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-07-13 15:31:53',
                'updated_at' => '2026-07-13 15:31:53',
                'house_id' => '1',
            ],
            [
                'id' => '22',
                'maintenance_bom_id' => '2',
                'product_id' => '151',
                'quantity' => '1.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-07-13 15:31:53',
                'updated_at' => '2026-07-13 15:31:53',
                'house_id' => '1',
            ],
            [
                'id' => '23',
                'maintenance_bom_id' => '2',
                'product_id' => '610',
                'quantity' => '1.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-07-13 15:31:53',
                'updated_at' => '2026-07-13 15:31:53',
                'house_id' => '1',
            ],
            [
                'id' => '24',
                'maintenance_bom_id' => '3',
                'product_id' => '632',
                'quantity' => '28.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-03 02:20:59',
                'updated_at' => '2026-08-03 03:06:27',
                'house_id' => null,
            ],
            [
                'id' => '26',
                'maintenance_bom_id' => '3',
                'product_id' => '607',
                'quantity' => '2.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-03 02:37:34',
                'updated_at' => '2026-08-03 03:06:27',
                'house_id' => null,
            ],
            [
                'id' => '28',
                'maintenance_bom_id' => '3',
                'product_id' => '571',
                'quantity' => '1.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-03 02:47:23',
                'updated_at' => '2026-08-03 03:06:27',
                'house_id' => null,
            ],
            [
                'id' => '29',
                'maintenance_bom_id' => '3',
                'product_id' => '197',
                'quantity' => '2.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-03 02:47:23',
                'updated_at' => '2026-08-03 03:06:27',
                'house_id' => null,
            ],
            [
                'id' => '30',
                'maintenance_bom_id' => '4',
                'product_id' => '632',
                'quantity' => '28.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-03 03:02:38',
                'updated_at' => '2026-08-10 02:52:31',
                'house_id' => null,
            ],
            [
                'id' => '31',
                'maintenance_bom_id' => '4',
                'product_id' => '607',
                'quantity' => '2.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-03 03:02:38',
                'updated_at' => '2026-08-10 02:52:31',
                'house_id' => null,
            ],
            [
                'id' => '32',
                'maintenance_bom_id' => '4',
                'product_id' => '571',
                'quantity' => '1.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-03 03:02:38',
                'updated_at' => '2026-08-10 02:52:31',
                'house_id' => null,
            ],
            [
                'id' => '33',
                'maintenance_bom_id' => '4',
                'product_id' => '197',
                'quantity' => '2.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-03 03:02:38',
                'updated_at' => '2026-08-10 02:52:31',
                'house_id' => null,
            ],
            [
                'id' => '34',
                'maintenance_bom_id' => '4',
                'product_id' => '639',
                'quantity' => '3.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-03 03:05:12',
                'updated_at' => '2026-08-10 02:52:31',
                'house_id' => null,
            ],
            [
                'id' => '35',
                'maintenance_bom_id' => '4',
                'product_id' => '551',
                'quantity' => '80.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-03 03:05:12',
                'updated_at' => '2026-08-10 02:52:31',
                'house_id' => null,
            ],
            [
                'id' => '36',
                'maintenance_bom_id' => '4',
                'product_id' => '637',
                'quantity' => '53.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-03 03:05:12',
                'updated_at' => '2026-08-10 02:52:31',
                'house_id' => null,
            ],
            [
                'id' => '39',
                'maintenance_bom_id' => '6',
                'product_id' => '632',
                'quantity' => '38.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-10 02:53:53',
                'updated_at' => '2026-08-10 04:53:53',
                'house_id' => null,
            ],
            [
                'id' => '40',
                'maintenance_bom_id' => '6',
                'product_id' => '773',
                'quantity' => '1.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-10 03:33:56',
                'updated_at' => '2026-08-10 04:53:53',
                'house_id' => null,
            ],
            [
                'id' => '41',
                'maintenance_bom_id' => '6',
                'product_id' => '785',
                'quantity' => '1.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-10 03:36:10',
                'updated_at' => '2026-08-10 04:53:53',
                'house_id' => null,
            ],
            [
                'id' => '42',
                'maintenance_bom_id' => '7',
                'product_id' => '632',
                'quantity' => '38.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-10 04:47:53',
                'updated_at' => '2026-08-10 04:50:25',
                'house_id' => null,
            ],
            [
                'id' => '43',
                'maintenance_bom_id' => '7',
                'product_id' => '773',
                'quantity' => '1.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-10 04:47:53',
                'updated_at' => '2026-08-10 04:50:25',
                'house_id' => null,
            ],
            [
                'id' => '44',
                'maintenance_bom_id' => '7',
                'product_id' => '785',
                'quantity' => '1.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-10 04:47:53',
                'updated_at' => '2026-08-10 04:50:25',
                'house_id' => null,
            ],
            [
                'id' => '45',
                'maintenance_bom_id' => '7',
                'product_id' => '786',
                'quantity' => '1.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-10 04:49:10',
                'updated_at' => '2026-08-10 04:50:25',
                'house_id' => null,
            ],
            [
                'id' => '46',
                'maintenance_bom_id' => '7',
                'product_id' => '774',
                'quantity' => '1.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-10 04:49:20',
                'updated_at' => '2026-08-10 04:50:25',
                'house_id' => null,
            ],
            [
                'id' => '47',
                'maintenance_bom_id' => '7',
                'product_id' => '640',
                'quantity' => '208.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-10 04:50:12',
                'updated_at' => '2026-08-10 04:50:25',
                'house_id' => null,
            ],
            [
                'id' => '48',
                'maintenance_bom_id' => '8',
                'product_id' => '632',
                'quantity' => '38.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-10 04:51:54',
                'updated_at' => '2026-08-10 04:52:51',
                'house_id' => null,
            ],
            [
                'id' => '49',
                'maintenance_bom_id' => '8',
                'product_id' => '773',
                'quantity' => '1.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-10 04:51:54',
                'updated_at' => '2026-08-10 04:52:51',
                'house_id' => null,
            ],
            [
                'id' => '50',
                'maintenance_bom_id' => '8',
                'product_id' => '785',
                'quantity' => '1.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-10 04:51:54',
                'updated_at' => '2026-08-10 04:52:51',
                'house_id' => null,
            ],
            [
                'id' => '51',
                'maintenance_bom_id' => '8',
                'product_id' => '786',
                'quantity' => '1.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-10 04:51:54',
                'updated_at' => '2026-08-10 04:52:51',
                'house_id' => null,
            ],
            [
                'id' => '52',
                'maintenance_bom_id' => '8',
                'product_id' => '774',
                'quantity' => '1.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-10 04:51:54',
                'updated_at' => '2026-08-10 04:52:51',
                'house_id' => null,
            ],
            [
                'id' => '53',
                'maintenance_bom_id' => '8',
                'product_id' => '640',
                'quantity' => '208.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-10 04:51:54',
                'updated_at' => '2026-08-10 04:52:51',
                'house_id' => null,
            ],
            [
                'id' => '54',
                'maintenance_bom_id' => '8',
                'product_id' => '634',
                'quantity' => '90.00',
                'backup_quantity' => '0.00',
                'note' => '',
                'created_at' => '2026-08-10 04:52:19',
                'updated_at' => '2026-08-10 04:52:51',
                'house_id' => null,
            ],
        ];
        
        foreach(array_chunk($data, 100) as $chunk) {
            DB::table('maintenance_bom_items')->insert($chunk);
        }
    }
}
