<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PurchasePlanHistoriesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('purchase_plan_histories')->truncate();
        
        $data = [
            [
                'id' => '7',
                'purchase_plan_id' => '7',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu. Tự động đề xuất do tồn kho (0) <= tồn tối thiểu (0).',
                'changed_by' => '1',
                'created_at' => '2026-08-09 04:01:51',
                'updated_at' => '2026-08-09 04:01:51',
            ],
            [
                'id' => '8',
                'purchase_plan_id' => '8',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu. Tự động đề xuất do tồn kho (7.00) <= tồn tối thiểu (7).',
                'changed_by' => '1',
                'created_at' => '2026-08-09 04:01:51',
                'updated_at' => '2026-08-09 04:01:51',
            ],
            [
                'id' => '9',
                'purchase_plan_id' => '9',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu. Tự động đề xuất do tồn kho (8.00) <= tồn tối thiểu (30).',
                'changed_by' => '1',
                'created_at' => '2026-08-09 04:01:51',
                'updated_at' => '2026-08-09 04:01:51',
            ],
            [
                'id' => '10',
                'purchase_plan_id' => '10',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '11',
                'purchase_plan_id' => '11',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '12',
                'purchase_plan_id' => '12',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '13',
                'purchase_plan_id' => '13',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '14',
                'purchase_plan_id' => '14',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '15',
                'purchase_plan_id' => '15',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '16',
                'purchase_plan_id' => '16',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '17',
                'purchase_plan_id' => '17',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '18',
                'purchase_plan_id' => '18',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '19',
                'purchase_plan_id' => '19',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '20',
                'purchase_plan_id' => '20',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '21',
                'purchase_plan_id' => '21',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '22',
                'purchase_plan_id' => '22',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '23',
                'purchase_plan_id' => '23',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '24',
                'purchase_plan_id' => '24',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '25',
                'purchase_plan_id' => '25',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '26',
                'purchase_plan_id' => '26',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '27',
                'purchase_plan_id' => '27',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '28',
                'purchase_plan_id' => '28',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '29',
                'purchase_plan_id' => '29',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '30',
                'purchase_plan_id' => '30',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '31',
                'purchase_plan_id' => '31',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '32',
                'purchase_plan_id' => '32',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '33',
                'purchase_plan_id' => '33',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '34',
                'purchase_plan_id' => '34',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '35',
                'purchase_plan_id' => '35',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '36',
                'purchase_plan_id' => '36',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '37',
                'purchase_plan_id' => '37',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '38',
                'purchase_plan_id' => '38',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '39',
                'purchase_plan_id' => '39',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '40',
                'purchase_plan_id' => '40',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '41',
                'purchase_plan_id' => '41',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '42',
                'purchase_plan_id' => '42',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '43',
                'purchase_plan_id' => '43',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '44',
                'purchase_plan_id' => '44',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '45',
                'purchase_plan_id' => '45',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '46',
                'purchase_plan_id' => '46',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '47',
                'purchase_plan_id' => '47',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '48',
                'purchase_plan_id' => '48',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '49',
                'purchase_plan_id' => '49',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '50',
                'purchase_plan_id' => '50',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '51',
                'purchase_plan_id' => '51',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '52',
                'purchase_plan_id' => '52',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '53',
                'purchase_plan_id' => '53',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '54',
                'purchase_plan_id' => '54',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '55',
                'purchase_plan_id' => '55',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '56',
                'purchase_plan_id' => '56',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '57',
                'purchase_plan_id' => '57',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '58',
                'purchase_plan_id' => '58',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '59',
                'purchase_plan_id' => '59',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '60',
                'purchase_plan_id' => '60',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '61',
                'purchase_plan_id' => '61',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '62',
                'purchase_plan_id' => '62',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '63',
                'purchase_plan_id' => '63',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '64',
                'purchase_plan_id' => '64',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '65',
                'purchase_plan_id' => '65',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '66',
                'purchase_plan_id' => '66',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '67',
                'purchase_plan_id' => '67',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '68',
                'purchase_plan_id' => '68',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '69',
                'purchase_plan_id' => '69',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '70',
                'purchase_plan_id' => '70',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '71',
                'purchase_plan_id' => '71',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '72',
                'purchase_plan_id' => '72',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '73',
                'purchase_plan_id' => '73',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '74',
                'purchase_plan_id' => '74',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '75',
                'purchase_plan_id' => '75',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '76',
                'purchase_plan_id' => '76',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '77',
                'purchase_plan_id' => '77',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '78',
                'purchase_plan_id' => '78',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:42',
                'updated_at' => '2026-08-10 04:17:42',
            ],
            [
                'id' => '79',
                'purchase_plan_id' => '79',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '80',
                'purchase_plan_id' => '80',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '81',
                'purchase_plan_id' => '81',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '82',
                'purchase_plan_id' => '82',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '83',
                'purchase_plan_id' => '83',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '84',
                'purchase_plan_id' => '84',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '85',
                'purchase_plan_id' => '85',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '86',
                'purchase_plan_id' => '86',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '87',
                'purchase_plan_id' => '87',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '88',
                'purchase_plan_id' => '88',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '89',
                'purchase_plan_id' => '89',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '90',
                'purchase_plan_id' => '90',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '91',
                'purchase_plan_id' => '91',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '92',
                'purchase_plan_id' => '92',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '93',
                'purchase_plan_id' => '93',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '94',
                'purchase_plan_id' => '94',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '95',
                'purchase_plan_id' => '95',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '96',
                'purchase_plan_id' => '96',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '97',
                'purchase_plan_id' => '97',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '98',
                'purchase_plan_id' => '98',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '99',
                'purchase_plan_id' => '99',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '100',
                'purchase_plan_id' => '100',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '101',
                'purchase_plan_id' => '101',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '102',
                'purchase_plan_id' => '102',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '103',
                'purchase_plan_id' => '103',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '104',
                'purchase_plan_id' => '104',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '105',
                'purchase_plan_id' => '105',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '106',
                'purchase_plan_id' => '106',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '107',
                'purchase_plan_id' => '107',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '108',
                'purchase_plan_id' => '108',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '109',
                'purchase_plan_id' => '109',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '110',
                'purchase_plan_id' => '110',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '111',
                'purchase_plan_id' => '111',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '112',
                'purchase_plan_id' => '112',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '113',
                'purchase_plan_id' => '113',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '114',
                'purchase_plan_id' => '114',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '115',
                'purchase_plan_id' => '115',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '116',
                'purchase_plan_id' => '116',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '117',
                'purchase_plan_id' => '117',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '118',
                'purchase_plan_id' => '118',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '119',
                'purchase_plan_id' => '119',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '120',
                'purchase_plan_id' => '120',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '121',
                'purchase_plan_id' => '121',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '122',
                'purchase_plan_id' => '122',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '123',
                'purchase_plan_id' => '123',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '124',
                'purchase_plan_id' => '124',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '125',
                'purchase_plan_id' => '125',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '126',
                'purchase_plan_id' => '126',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '127',
                'purchase_plan_id' => '127',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '128',
                'purchase_plan_id' => '128',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '129',
                'purchase_plan_id' => '129',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '130',
                'purchase_plan_id' => '130',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '131',
                'purchase_plan_id' => '131',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '132',
                'purchase_plan_id' => '132',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '133',
                'purchase_plan_id' => '133',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '134',
                'purchase_plan_id' => '134',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '135',
                'purchase_plan_id' => '135',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '136',
                'purchase_plan_id' => '136',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '137',
                'purchase_plan_id' => '137',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '138',
                'purchase_plan_id' => '138',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '139',
                'purchase_plan_id' => '139',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '140',
                'purchase_plan_id' => '140',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '141',
                'purchase_plan_id' => '141',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '142',
                'purchase_plan_id' => '142',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '143',
                'purchase_plan_id' => '143',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '144',
                'purchase_plan_id' => '144',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '145',
                'purchase_plan_id' => '145',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '146',
                'purchase_plan_id' => '146',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '147',
                'purchase_plan_id' => '147',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '148',
                'purchase_plan_id' => '148',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '149',
                'purchase_plan_id' => '149',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '150',
                'purchase_plan_id' => '150',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '151',
                'purchase_plan_id' => '151',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '152',
                'purchase_plan_id' => '152',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '153',
                'purchase_plan_id' => '153',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '154',
                'purchase_plan_id' => '154',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '155',
                'purchase_plan_id' => '155',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '156',
                'purchase_plan_id' => '156',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '157',
                'purchase_plan_id' => '157',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '158',
                'purchase_plan_id' => '158',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '159',
                'purchase_plan_id' => '159',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '160',
                'purchase_plan_id' => '160',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '161',
                'purchase_plan_id' => '161',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '162',
                'purchase_plan_id' => '162',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '163',
                'purchase_plan_id' => '163',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '164',
                'purchase_plan_id' => '164',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '165',
                'purchase_plan_id' => '165',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '166',
                'purchase_plan_id' => '166',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '167',
                'purchase_plan_id' => '167',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '168',
                'purchase_plan_id' => '168',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '169',
                'purchase_plan_id' => '169',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '170',
                'purchase_plan_id' => '170',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '171',
                'purchase_plan_id' => '171',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '172',
                'purchase_plan_id' => '172',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '173',
                'purchase_plan_id' => '173',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '174',
                'purchase_plan_id' => '174',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '175',
                'purchase_plan_id' => '175',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '176',
                'purchase_plan_id' => '176',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '177',
                'purchase_plan_id' => '177',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '178',
                'purchase_plan_id' => '178',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '179',
                'purchase_plan_id' => '179',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '180',
                'purchase_plan_id' => '180',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '181',
                'purchase_plan_id' => '181',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '182',
                'purchase_plan_id' => '182',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '183',
                'purchase_plan_id' => '183',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '184',
                'purchase_plan_id' => '184',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '185',
                'purchase_plan_id' => '185',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '186',
                'purchase_plan_id' => '186',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '187',
                'purchase_plan_id' => '187',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '188',
                'purchase_plan_id' => '188',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '189',
                'purchase_plan_id' => '189',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '190',
                'purchase_plan_id' => '190',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '191',
                'purchase_plan_id' => '191',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '192',
                'purchase_plan_id' => '192',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '193',
                'purchase_plan_id' => '193',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '194',
                'purchase_plan_id' => '194',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '195',
                'purchase_plan_id' => '195',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '196',
                'purchase_plan_id' => '196',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '197',
                'purchase_plan_id' => '197',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '198',
                'purchase_plan_id' => '198',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '199',
                'purchase_plan_id' => '199',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '200',
                'purchase_plan_id' => '200',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '201',
                'purchase_plan_id' => '201',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
            [
                'id' => '202',
                'purchase_plan_id' => '202',
                'old_status' => null,
                'new_status' => 'pending',
                'old_quantity' => '0.00',
                'new_quantity' => '0.00',
                'notes' => 'Khởi tạo đề xuất ban đầu.',
                'changed_by' => '1',
                'created_at' => '2026-08-10 04:17:43',
                'updated_at' => '2026-08-10 04:17:43',
            ],
        ];
        
        foreach(array_chunk($data, 100) as $chunk) {
            DB::table('purchase_plan_histories')->insert($chunk);
        }
    }
}
