<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StockOutItemsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('stock_out_items')->truncate();
        
        $data = [
            [
                'id' => '1',
                'stock_out_id' => '1',
                'product_id' => '15',
                'batch_number' => '',
                'expiry_date' => '2026-06-25',
                'warehouse_location' => '',
                'quantity' => '10.0000',
                'unit_price' => '131000.00',
                'vat_rate' => '0.00',
                'total_amount' => '1310000.00',
                'created_at' => '2026-06-28 12:34:49',
                'updated_at' => '2026-06-28 12:34:49',
                'requested_quantity' => '10.0000',
                'recovered_quantity' => '10.0000',
                'item_note' => '',
            ],
            [
                'id' => '2',
                'stock_out_id' => '2',
                'product_id' => '5',
                'batch_number' => '',
                'expiry_date' => '2026-09-15',
                'warehouse_location' => '',
                'quantity' => '10.0000',
                'unit_price' => '479000.00',
                'vat_rate' => '0.00',
                'total_amount' => '4790000.00',
                'created_at' => '2026-06-28 12:37:49',
                'updated_at' => '2026-06-28 12:37:49',
                'requested_quantity' => '10.0000',
                'recovered_quantity' => '10.0000',
                'item_note' => '',
            ],
            [
                'id' => '3',
                'stock_out_id' => '3',
                'product_id' => '16',
                'batch_number' => '',
                'expiry_date' => '2026-10-21',
                'warehouse_location' => '',
                'quantity' => '10.0000',
                'unit_price' => '93000.00',
                'vat_rate' => '0.00',
                'total_amount' => '930000.00',
                'created_at' => '2026-06-28 13:01:50',
                'updated_at' => '2026-06-28 13:01:50',
                'requested_quantity' => '10.0000',
                'recovered_quantity' => '10.0000',
                'item_note' => '',
            ],
            [
                'id' => '4',
                'stock_out_id' => '4',
                'product_id' => '215',
                'batch_number' => '-',
                'expiry_date' => '2027-07-13',
                'warehouse_location' => '',
                'quantity' => '1.0000',
                'unit_price' => '0.00',
                'vat_rate' => '0.00',
                'total_amount' => '0.00',
                'created_at' => '2026-07-18 00:26:21',
                'updated_at' => '2026-07-18 00:26:21',
                'requested_quantity' => '1.0000',
                'recovered_quantity' => '0.0000',
                'item_note' => '',
            ],
            [
                'id' => '5',
                'stock_out_id' => '4',
                'product_id' => '132',
                'batch_number' => '-',
                'expiry_date' => '2027-07-13',
                'warehouse_location' => '',
                'quantity' => '5.0000',
                'unit_price' => '0.00',
                'vat_rate' => '0.00',
                'total_amount' => '0.00',
                'created_at' => '2026-07-18 00:26:21',
                'updated_at' => '2026-07-18 00:26:21',
                'requested_quantity' => '5.0000',
                'recovered_quantity' => '5.0000',
                'item_note' => '',
            ],
            [
                'id' => '63',
                'stock_out_id' => '25',
                'product_id' => '632',
                'batch_number' => null,
                'expiry_date' => null,
                'warehouse_location' => '',
                'quantity' => '28.0000',
                'unit_price' => '0.00',
                'vat_rate' => '0.00',
                'total_amount' => '0.00',
                'created_at' => '2026-08-09 08:02:56',
                'updated_at' => '2026-08-09 08:02:56',
                'requested_quantity' => '28.0000',
                'recovered_quantity' => '0.0000',
                'item_note' => '',
            ],
            [
                'id' => '64',
                'stock_out_id' => '25',
                'product_id' => '607',
                'batch_number' => null,
                'expiry_date' => null,
                'warehouse_location' => '',
                'quantity' => '2.0000',
                'unit_price' => '0.00',
                'vat_rate' => '0.00',
                'total_amount' => '0.00',
                'created_at' => '2026-08-09 08:02:56',
                'updated_at' => '2026-08-09 08:02:56',
                'requested_quantity' => '2.0000',
                'recovered_quantity' => '0.0000',
                'item_note' => '',
            ],
            [
                'id' => '65',
                'stock_out_id' => '25',
                'product_id' => '571',
                'batch_number' => '',
                'expiry_date' => null,
                'warehouse_location' => '',
                'quantity' => '1.0000',
                'unit_price' => '0.00',
                'vat_rate' => '0.00',
                'total_amount' => '0.00',
                'created_at' => '2026-08-09 08:02:56',
                'updated_at' => '2026-08-09 08:02:56',
                'requested_quantity' => '1.0000',
                'recovered_quantity' => '0.0000',
                'item_note' => '',
            ],
            [
                'id' => '66',
                'stock_out_id' => '25',
                'product_id' => '197',
                'batch_number' => '',
                'expiry_date' => null,
                'warehouse_location' => '',
                'quantity' => '2.0000',
                'unit_price' => '0.00',
                'vat_rate' => '0.00',
                'total_amount' => '0.00',
                'created_at' => '2026-08-09 08:02:56',
                'updated_at' => '2026-08-09 08:02:56',
                'requested_quantity' => '2.0000',
                'recovered_quantity' => '0.0000',
                'item_note' => '',
            ],
        ];
        
        foreach(array_chunk($data, 100) as $chunk) {
            DB::table('stock_out_items')->insert($chunk);
        }
    }
}
