<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StockOutsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('stock_outs')->truncate();
        
        $data = [
            [
                'id' => '1',
                'code' => 'SO-20260628-0001',
                'customer_name' => 'BCH VINALPHA',
                'receiver_name' => 'LÊ HOÀNG NAM',
                'receiver_contact' => 'ĐẶNG VĂN A',
                'asset_code' => 'V-XX1243',
                'type' => 'repair',
                'status' => 'completed',
                'note' => 'BẢO DƯỠNG ĐỊNH KỲ',
                'created_by' => '3',
                'created_at' => '2026-06-28 12:34:48',
                'updated_at' => '2026-06-28 12:34:48',
                'project_name' => 'HÓC MÔN',
                'document_number' => '',
                'license_plate' => '',
                'km_number' => '',
                'operating_hours' => '',
                'device_name' => '',
                'department' => 'BCH VINALPHA',
                'warehouse_keeper' => '',
                'supervisor_qltb' => '',
                'supervisor_ca' => '',
                'house_id' => null,
                'maintenance_plan_id' => null,
                'repair_staff' => null,
                'operator_name' => null,
            ],
            [
                'id' => '2',
                'code' => 'SO-20260628-0002',
                'customer_name' => 'BCH VINALPHA',
                'receiver_name' => 'LÊ HOÀNG NAM',
                'receiver_contact' => 'Nguyễn văn A',
                'asset_code' => 'V-XX0054',
                'type' => 'repair',
                'status' => 'completed',
                'note' => 'BẢO DƯỠNG ĐỊNH KỲ',
                'created_by' => '3',
                'created_at' => '2026-06-28 12:37:49',
                'updated_at' => '2026-06-28 12:37:49',
                'project_name' => 'HÓC MÔN',
                'document_number' => 'XX0054.3.SC',
                'license_plate' => '',
                'km_number' => '',
                'operating_hours' => '505',
                'device_name' => '',
                'department' => 'BCH VINALPHA',
                'warehouse_keeper' => '',
                'supervisor_qltb' => '',
                'supervisor_ca' => '',
                'house_id' => null,
                'maintenance_plan_id' => null,
                'repair_staff' => null,
                'operator_name' => null,
            ],
            [
                'id' => '3',
                'code' => 'SO-20260628-0003',
                'customer_name' => 'BCH VINALPHA',
                'receiver_name' => 'LÊ HOÀNG NAM',
                'receiver_contact' => '',
                'asset_code' => '',
                'type' => 'repair',
                'status' => 'completed',
                'note' => 'BẢO DƯỠNG ĐỊNH KỲ',
                'created_by' => '3',
                'created_at' => '2026-06-28 13:01:49',
                'updated_at' => '2026-06-28 13:01:49',
                'project_name' => 'HÓC MÔN',
                'document_number' => '',
                'license_plate' => '',
                'km_number' => '',
                'operating_hours' => '',
                'device_name' => '',
                'department' => 'TỔ ĐỘI KTSC VINALPHA',
                'warehouse_keeper' => 'ĐẶNG HỮU HÒA',
                'supervisor_qltb' => 'NGUYỄN HOÀNG NAM',
                'supervisor_ca' => 'LÊ ĐÌNH HƯƠNG',
                'house_id' => null,
                'maintenance_plan_id' => null,
                'repair_staff' => null,
                'operator_name' => null,
            ],
            [
                'id' => '4',
                'code' => 'SO-20260718-0001',
                'customer_name' => 'BCH VINALPHA',
                'receiver_name' => 'LÊ HOÀNG NAM',
                'receiver_contact' => '',
                'asset_code' => '',
                'type' => 'repair',
                'status' => 'completed',
                'note' => 'BẢO DƯỠNG ĐỊNH KỲ',
                'created_by' => '3',
                'created_at' => '2026-07-18 00:26:21',
                'updated_at' => '2026-07-18 00:26:21',
                'project_name' => 'HÓC MÔN',
                'document_number' => '',
                'license_plate' => '',
                'km_number' => '',
                'operating_hours' => '',
                'device_name' => '',
                'department' => 'TỔ ĐỘI KTSC VINALPHA',
                'warehouse_keeper' => 'HÒA',
                'supervisor_qltb' => 'HƯƠNG',
                'supervisor_ca' => 'NAM',
                'house_id' => '1',
                'maintenance_plan_id' => null,
                'repair_staff' => null,
                'operator_name' => null,
            ],
            [
                'id' => '25',
                'code' => 'SO-20260809-0001',
                'customer_name' => 'BCH VINALPHA',
                'receiver_name' => 'LÊ HOÀNG NAM',
                'receiver_contact' => 'Đặng thị Bích Ngà',
                'asset_code' => '4c-0069',
                'type' => 'repair',
                'status' => 'completed',
                'note' => 'BẢO DƯỠNG ĐỊNH KỲ',
                'created_by' => '1',
                'created_at' => '2026-08-09 08:02:56',
                'updated_at' => '2026-08-09 08:02:56',
                'project_name' => 'HÓC MÔN',
                'document_number' => '4c-0069.5.sc',
                'license_plate' => '',
                'km_number' => '500',
                'operating_hours' => '',
                'device_name' => '4C',
                'department' => 'BCH VINALPHA',
                'warehouse_keeper' => 'ĐẶNG HỮU HÒA',
                'supervisor_qltb' => 'LÊ HOÀNG NAM',
                'supervisor_ca' => 'LÊ ĐÌNH HƯƠNG',
                'house_id' => '1',
                'maintenance_plan_id' => null,
                'repair_staff' => 'THIỀU THANH HIỀN',
                'operator_name' => 'BÙI VĂN HUẤN',
            ],
        ];
        
        foreach(array_chunk($data, 100) as $chunk) {
            DB::table('stock_outs')->insert($chunk);
        }
    }
}
