<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SystemModulesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('system_modules')->truncate();
        
        $data = [
            [
                'id' => '1',
                'group_name' => '1. Thông tin NCC/KH',
                'route_name' => 'warehouse.contacts',
                'label' => 'Quản lý thông tin Đối tác/Khách hàng',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '2',
                'group_name' => '2. Kho',
                'route_name' => 'warehouse.stock-in',
                'label' => 'Nhập kho',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '3',
                'group_name' => '2. Kho',
                'route_name' => 'warehouse.stock-out',
                'label' => 'Xuất kho',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '4',
                'group_name' => '2. Kho',
                'route_name' => 'warehouse.inventory',
                'label' => 'Tồn kho',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '5',
                'group_name' => '2. Kho',
                'route_name' => 'warehouse.stock-transfer.index',
                'label' => 'Chuyển kho',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '6',
                'group_name' => '2. Kho',
                'route_name' => 'warehouse.stock-recovery-report',
                'label' => 'Thu hồi phế phẩm',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '7',
                'group_name' => '2. Kho',
                'route_name' => 'warehouse.stock-count',
                'label' => 'Kiểm kê kho',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '8',
                'group_name' => '2. Kho',
                'route_name' => 'warehouse.settings.warehouses',
                'label' => 'Cấu hình kho',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '9',
                'group_name' => '3. Danh mục vật tư',
                'route_name' => 'warehouse.product-catalog',
                'label' => 'Danh mục vật tư',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '10',
                'group_name' => '3. Danh mục vật tư',
                'route_name' => 'warehouse.asset-manager',
                'label' => 'Danh mục thiết bị & tài sản',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '11',
                'group_name' => '4. Theo dõi bảo dưỡng',
                'route_name' => 'warehouse.maintenance-dashboard',
                'label' => 'Dashboard Tổng Quan',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '12',
                'group_name' => '4. Theo dõi bảo dưỡng',
                'route_name' => 'warehouse.asset-odo-log',
                'label' => 'Cập nhật giờ Odo',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '13',
                'group_name' => '4. Theo dõi bảo dưỡng',
                'route_name' => 'warehouse.maintenance-rules',
                'label' => 'Cấp bảo dưỡng và chu kỳ',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '14',
                'group_name' => '4. Theo dõi bảo dưỡng',
                'route_name' => 'warehouse.maintenance-tracking',
                'label' => 'Theo dõi bảo dưỡng tự động',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '15',
                'group_name' => '4. Theo dõi bảo dưỡng',
                'route_name' => 'warehouse.maintenance-plans',
                'label' => 'Lập kế hoạch bảo dưỡng',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '16',
                'group_name' => '4. Theo dõi bảo dưỡng',
                'route_name' => 'warehouse.maintenance-tickets',
                'label' => 'Phiếu thực hiện bảo dưỡng',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '17',
                'group_name' => '5. Kế hoạch & Mua hàng',
                'route_name' => 'warehouse.purchase-plan',
                'label' => 'Quản lý Kế hoạch',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '18',
                'group_name' => '5. Kế hoạch & Mua hàng',
                'route_name' => 'warehouse.purchase-plan.history',
                'label' => 'Lịch sử mua hàng',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '19',
                'group_name' => '6. Báo cáo',
                'route_name' => 'warehouse.reports.transaction-detail',
                'label' => 'Báo cáo chi tiết giao dịch',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '20',
                'group_name' => '6. Báo cáo',
                'route_name' => 'warehouse.reports.stock',
                'label' => 'Báo cáo kho',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '21',
                'group_name' => '7. Khác',
                'route_name' => 'warehouse.chat',
                'label' => 'Chat kho',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '22',
                'group_name' => '8. Trung tâm HR',
                'route_name' => 'hr.dashboard',
                'label' => 'Bảng điều khiển HR',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '23',
                'group_name' => '8. Trung tâm HR',
                'route_name' => 'hr.projects',
                'label' => 'Quản lý Dự án (Ngôi nhà)',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '24',
                'group_name' => '8. Trung tâm HR',
                'route_name' => 'hr.permissions',
                'label' => 'Phân quyền Hệ thống',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '25',
                'group_name' => '8. Trung tâm HR',
                'route_name' => 'hr.notifications',
                'label' => 'Quản lý Thông báo',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '26',
                'group_name' => '8. Trung tâm HR',
                'route_name' => 'hr.global-report',
                'label' => 'Báo cáo Tổng hợp',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
            [
                'id' => '27',
                'group_name' => '8. Trung tâm HR',
                'route_name' => 'hr.users.index',
                'label' => 'Quản lý Nhân viên',
                'is_active' => '1',
                'created_at' => '2026-07-05 15:47:09',
                'updated_at' => '2026-07-05 15:47:09',
            ],
        ];
        
        foreach(array_chunk($data, 100) as $chunk) {
            DB::table('system_modules')->insert($chunk);
        }
    }
}
