<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->truncate();
        
        $data = [
            [
                'id' => '1',
                'code' => '4022605',
                'phone' => '0123456789',
                'name' => 'ĐẶNG HỮU HÒA',
                'username' => '0708091050',
                'email' => 'admin@example.com',
                'role' => 'admin',
                'department' => 'KHO',
                'status' => 'active',
                'permissions' => '[\"warehouse.contacts\", \"warehouse.stock-in\", \"warehouse.stock-out\", \"warehouse.inventory\", \"warehouse.stock-transfer.index\", \"warehouse.stock-recovery-report\", \"warehouse.stock-count\", \"warehouse.settings.warehouses\", \"warehouse.product-catalog\", \"warehouse.asset-manager\", \"warehouse.maintenance-dashboard\", \"warehouse.asset-odo-log\", \"warehouse.maintenance-rules\", \"warehouse.maintenance-tracking\", \"warehouse.maintenance-plans\", \"warehouse.maintenance-tickets\", \"warehouse.purchase-plan\", \"warehouse.purchase-plan.history\", \"warehouse.reports.transaction-detail\", \"warehouse.reports.stock\", \"warehouse.chat\", \"hr.dashboard\", \"hr.projects\", \"hr.permissions\", \"hr.notifications\", \"hr.global-report\", \"hr.users.index\"]',
                'avatar' => null,
                'hire_date' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$wazgsGGIJGDkRTxJLiPnn.DRmbfCA5eJP3uF8VeOCA6/AG3oRKoWG',
                'remember_token' => 'rsSYdnP6zbDfMyyB0fJr32k1UDIWCLy9zsNo5qshBPdGwbHgk59wRSvlrude',
                'created_at' => '2026-06-22 01:00:09',
                'updated_at' => '2026-08-10 02:00:43',
                'allowed_houses' => '[\"1\", \"2\", \"3\", \"4\", \"5\"]',
                'current_house_id' => '1',
                'last_read_chat_at' => '2026-08-09 01:09:04',
            ],
            [
                'id' => '2',
                'code' => '3992571',
                'phone' => '0987654321',
                'name' => 'LÊ CÔNG HOAN',
                'username' => '0933828687',
                'email' => 'user@example.com',
                'role' => 'staff',
                'department' => 'KTSC',
                'status' => 'active',
                'permissions' => '[]',
                'avatar' => null,
                'hire_date' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$s1gQmL0vjt1Zvu9P9elb/.OsnYYe69IP16PkK5SzOU61PUTkljk2O',
                'remember_token' => null,
                'created_at' => '2026-06-22 01:00:09',
                'updated_at' => '2026-08-09 00:56:48',
                'allowed_houses' => '[\"1\"]',
                'current_house_id' => null,
                'last_read_chat_at' => null,
            ],
            [
                'id' => '3',
                'code' => 'ADM001',
                'phone' => '0708091050',
                'name' => 'Admin',
                'username' => null,
                'email' => 'admin@erp.local',
                'role' => 'admin',
                'department' => null,
                'status' => 'active',
                'permissions' => null,
                'avatar' => null,
                'hire_date' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$VQr3Yqm7tr1xqZ7RtexkA.dRJRFLjCPDSGit1VbCqe/LuXym0GSR.',
                'remember_token' => 'YAnF3atHCSRKuAWGAipdIlqU3PnZBpn2ebKJqF2UTuKbU6c0HufwBN7pObow',
                'created_at' => '2026-06-22 01:00:09',
                'updated_at' => '2026-08-09 00:17:26',
                'allowed_houses' => '[1, 2, 3, 4, 5]',
                'current_house_id' => '5',
                'last_read_chat_at' => '2026-08-03 07:50:18',
            ],
            [
                'id' => '7',
                'code' => '3960600',
                'phone' => null,
                'name' => 'HỒ MINH HẢI',
                'username' => '0707404044',
                'email' => 'test1@test.com',
                'role' => 'staff',
                'department' => 'KTSC',
                'status' => 'active',
                'permissions' => '[]',
                'avatar' => null,
                'hire_date' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$jQgDo3LNTTPTncfFqKhlpOFF7k3ELvn758Or1t5EXvu4xuolKIfQ2',
                'remember_token' => null,
                'created_at' => '2026-07-05 15:27:43',
                'updated_at' => '2026-08-09 01:01:11',
                'allowed_houses' => '[\"1\"]',
                'current_house_id' => '1',
                'last_read_chat_at' => null,
            ],
            [
                'id' => '8',
                'code' => '3960602',
                'phone' => null,
                'name' => 'NGUYỄN CHÍ NGUYÊN',
                'username' => '0347533551',
                'email' => 'test2@test.com',
                'role' => 'staff',
                'department' => 'KTSC',
                'status' => 'active',
                'permissions' => '[]',
                'avatar' => null,
                'hire_date' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$6EHpPNIWt0H2LH4FbVFDsOpDpHJeAggE7mYpTuoM9xW5HHctI3sSu',
                'remember_token' => null,
                'created_at' => '2026-07-05 15:27:43',
                'updated_at' => '2026-08-09 01:01:29',
                'allowed_houses' => '[\"1\"]',
                'current_house_id' => '2',
                'last_read_chat_at' => null,
            ],
            [
                'id' => '9',
                'code' => '3949027',
                'phone' => null,
                'name' => 'TRẦN NGỌC HUY',
                'username' => '0332033929',
                'email' => 'hr@test.com',
                'role' => 'staff',
                'department' => 'KTSC',
                'status' => 'active',
                'permissions' => '[\"warehouse.contacts\", \"warehouse.stock-in\", \"warehouse.stock-out\", \"warehouse.inventory\", \"warehouse.product-catalog\", \"warehouse.reports.transaction-detail\", \"warehouse.chat\"]',
                'avatar' => null,
                'hire_date' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$EnrxalqrfbsZu5aA5jdB2uNxZS1vTpIbEXBl2UccbZpX6UfCltGQa',
                'remember_token' => null,
                'created_at' => '2026-07-05 15:27:43',
                'updated_at' => '2026-08-09 00:59:01',
                'allowed_houses' => '[\"1\"]',
                'current_house_id' => '5',
                'last_read_chat_at' => null,
            ],
            [
                'id' => '10',
                'code' => '3960598',
                'phone' => null,
                'name' => 'NGUYỄN NGỌC MINH',
                'username' => '0827857631',
                'email' => null,
                'role' => 'staff',
                'department' => 'KTSC',
                'status' => 'active',
                'permissions' => '[]',
                'avatar' => null,
                'hire_date' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$JT6KdFVTUj51G/kQvhL5w.YVpsOryegiiHofuTZOYRDxJI13bIDkG',
                'remember_token' => null,
                'created_at' => '2026-08-09 01:00:44',
                'updated_at' => '2026-08-09 01:00:44',
                'allowed_houses' => '[\"1\"]',
                'current_house_id' => null,
                'last_read_chat_at' => null,
            ],
            [
                'id' => '11',
                'code' => '4005394',
                'phone' => null,
                'name' => 'NGUYỄN TẤN LỰC',
                'username' => '0349998457',
                'email' => null,
                'role' => 'staff',
                'department' => 'KTSC',
                'status' => 'active',
                'permissions' => '[]',
                'avatar' => null,
                'hire_date' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$CaK8xv/8IbbKAYkvOAe3SeHop6agJarSRPG1YPmqKVZ2CbFDjNzQy',
                'remember_token' => null,
                'created_at' => '2026-08-09 01:02:46',
                'updated_at' => '2026-08-09 01:02:46',
                'allowed_houses' => '[\"1\"]',
                'current_house_id' => null,
                'last_read_chat_at' => null,
            ],
            [
                'id' => '12',
                'code' => '3960601',
                'phone' => null,
                'name' => 'ĐỖ MINH CƯỜNG',
                'username' => '0373973978',
                'email' => null,
                'role' => 'staff',
                'department' => 'KTSC',
                'status' => 'active',
                'permissions' => '[]',
                'avatar' => null,
                'hire_date' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$KRr/aCB2nXXWdcC.qwVEDOofm8.OySTg.IscWk6zFWzg6GftimSMy',
                'remember_token' => null,
                'created_at' => '2026-08-09 01:04:09',
                'updated_at' => '2026-08-09 01:04:09',
                'allowed_houses' => '[\"1\"]',
                'current_house_id' => null,
                'last_read_chat_at' => null,
            ],
            [
                'id' => '13',
                'code' => '3992574',
                'phone' => null,
                'name' => 'ĐẶNG THỊ BÍCH NGÀ',
                'username' => '0867162407',
                'email' => null,
                'role' => 'staff',
                'department' => 'KTSC',
                'status' => 'active',
                'permissions' => '[\"warehouse.stock-out\"]',
                'avatar' => null,
                'hire_date' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$J.lAw4ePlMHUE/UsOFypSelKW43XAWqple4hqoBaLr16FddKfnyGy',
                'remember_token' => 'y1sJRp9PS9tx19gjUTwX2vSXAJQZ4AJ6XaLXAjx25lmxPDU0EaA2y8Q1HhiR',
                'created_at' => '2026-08-09 01:05:49',
                'updated_at' => '2026-08-09 01:25:41',
                'allowed_houses' => '[\"1\"]',
                'current_house_id' => '1',
                'last_read_chat_at' => null,
            ],
            [
                'id' => '14',
                'code' => '3960593',
                'phone' => null,
                'name' => 'ĐINH XUÂN ANH',
                'username' => '0977963776',
                'email' => null,
                'role' => 'staff',
                'department' => 'KTSC',
                'status' => 'active',
                'permissions' => '[]',
                'avatar' => null,
                'hire_date' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$3c5oEj3hKc66oKhr3zQtFO/3T/jmeiNiI7iaq0IK01k8XkxhWBk02',
                'remember_token' => null,
                'created_at' => '2026-08-09 01:57:46',
                'updated_at' => '2026-08-09 01:57:46',
                'allowed_houses' => '[\"1\"]',
                'current_house_id' => null,
                'last_read_chat_at' => null,
            ],
            [
                'id' => '15',
                'code' => '4021913',
                'phone' => null,
                'name' => 'NGUYỄN THÀNH THỰC',
                'username' => null,
                'email' => null,
                'role' => 'staff',
                'department' => 'KTSC',
                'status' => 'active',
                'permissions' => '[]',
                'avatar' => null,
                'hire_date' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$W.dqrl3mBkgqcJS/vm93i.uul1iJxnySyXxaLjdrNpRzIuGNQJ5re',
                'remember_token' => null,
                'created_at' => '2026-08-09 01:58:32',
                'updated_at' => '2026-08-09 01:58:32',
                'allowed_houses' => '[\"1\"]',
                'current_house_id' => null,
                'last_read_chat_at' => null,
            ],
            [
                'id' => '16',
                'code' => '4025227',
                'phone' => null,
                'name' => 'BÙI THANH HUẤN',
                'username' => '0908783229',
                'email' => null,
                'role' => 'staff',
                'department' => 'KTSC',
                'status' => 'active',
                'permissions' => '[]',
                'avatar' => null,
                'hire_date' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$6RRzbKX36/T5nyRgEjN/VebExtxRAtdoeSyIbjLz6cSz0W088wHcS',
                'remember_token' => null,
                'created_at' => '2026-08-09 02:00:14',
                'updated_at' => '2026-08-09 02:00:14',
                'allowed_houses' => '[\"1\"]',
                'current_house_id' => null,
                'last_read_chat_at' => null,
            ],
            [
                'id' => '17',
                'code' => '4036818',
                'phone' => null,
                'name' => 'THIỀU THANH HIỀN',
                'username' => '096771165',
                'email' => null,
                'role' => 'staff',
                'department' => 'KTSC',
                'status' => 'active',
                'permissions' => '[]',
                'avatar' => null,
                'hire_date' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$iRcQwAlxTrcDsFQV89KJnOQS2CAa3vt5f8DOflN9gPsF.Mqa52MCG',
                'remember_token' => null,
                'created_at' => '2026-08-09 02:01:31',
                'updated_at' => '2026-08-09 02:01:31',
                'allowed_houses' => '[\"1\"]',
                'current_house_id' => null,
                'last_read_chat_at' => null,
            ],
            [
                'id' => '18',
                'code' => '4004334',
                'phone' => null,
                'name' => 'TRẦN VŨ LINH',
                'username' => '0967544389',
                'email' => null,
                'role' => 'staff',
                'department' => 'KTSC',
                'status' => 'active',
                'permissions' => '[]',
                'avatar' => null,
                'hire_date' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$82R3mBXmkUcM1zGwzRsRV.0OzV4N.63Y0bqmWfqEre1hNOLdyukTC',
                'remember_token' => null,
                'created_at' => '2026-08-09 02:02:37',
                'updated_at' => '2026-08-09 02:02:37',
                'allowed_houses' => '[\"1\"]',
                'current_house_id' => null,
                'last_read_chat_at' => null,
            ],
            [
                'id' => '19',
                'code' => '4114636',
                'phone' => null,
                'name' => 'HUỲNH NHẬT DANH',
                'username' => '0344173292',
                'email' => null,
                'role' => 'staff',
                'department' => 'KTSC',
                'status' => 'active',
                'permissions' => '[]',
                'avatar' => null,
                'hire_date' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$Np2Co/c6ceCorsbjfCr.cOphnw0THS5LakNbbes9mBf5tFUrDkJT2',
                'remember_token' => null,
                'created_at' => '2026-08-09 02:03:37',
                'updated_at' => '2026-08-09 02:03:37',
                'allowed_houses' => '[\"1\"]',
                'current_house_id' => null,
                'last_read_chat_at' => null,
            ],
        ];
        
        foreach(array_chunk($data, 100) as $chunk) {
            DB::table('users')->insert($chunk);
        }
    }
}
